/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ICollateralPool__initial__factory } from "./ICollateralPool__initial__factory";
export { ICollateralPool__latest__factory } from "./ICollateralPool__latest__factory";
