/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ICollateralPool__initial } from "./ICollateralPool__initial";
export type { ICollateralPool__latest } from "./ICollateralPool__latest";
