x-templates:
  base-svc: &base-svc
    image: ${CI_REGISTRY_IMAGE}:${DEPLOY_IMAGE_TAG}
    depends_on:
      db-postgres:
        condition: service_healthy
    restart: unless-stopped

services:
  core:
    <<: *base-svc
    container_name: ${COMPOSE_PROJECT_NAME}-core
    profiles: ["core"]
    command: ["node", "/app/packages/fasset-indexer-core/dist/src/run/run-indexer.js"]
    environment:
      DB_TYPE: postgres
      DB_HOST: db-postgres
      DB_PORT: 5432
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      CHAIN: ${CHAIN}
      RPC_URL: ${RPC_URL}
      RPC_API_KEY: ${RPC_API_KEY:-}
      CONFIG_PATH: /usr/src/app/config.json
    volumes:
      - ${CONFIG_PATH}:/usr/src/app/config.json
  watchdog:
    <<: *base-svc
    container_name: ${COMPOSE_PROJECT_NAME}-watchdog
    profiles: ["watchdog"]
    command: ["node", "/app/packages/fasset-indexer-core/dist/src/run/run-watchdog.js"]
    environment:
      DB_TYPE: postgres
      DB_HOST: db-postgres
      DB_PORT: 5432
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      CHAIN: ${CHAIN}
      RPC_URL: ${RPC_URL}
      RPC_API_KEY: ${RPC_API_KEY:-}
  dogecoin:
    <<: *base-svc
    container_name: ${COMPOSE_PROJECT_NAME}-dogecoin
    profiles: ["dogecoin"]
    command: ["node", "/app/packages/fasset-indexer-doge/dist/src/run/run-indexer.js"]
    environment:
      DB_TYPE: postgres
      DB_HOST: db-postgres
      DB_PORT: 5432
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DOGE_RPC_URL: ${RPC_URL}
      DOGE_RPC_API_KEY: ${RPC_API_KEY:-}
      DOGE_RPC_USER: ${RPC_USER:-}
      DOGE_RPC_PASSWORD: ${RPC_PASSWORD:-}
      DOGE_MIN_BLOCK_NUMBER: ${DOGE_MIN_BLOCK_NUMBER}
  api:
    <<: *base-svc
    container_name: ${COMPOSE_PROJECT_NAME}-api
    profiles: ["api"]
    command: ["node", "/app/packages/fasset-indexer-api/dist/src/main"]
    environment:
      DB_TYPE: postgres
      DB_HOST: db-postgres
      DB_PORT: 5432
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      API_ROOT_PATH: ${API_ROOT_PATH:-}
    ports:
      - "${API_PORT}:3000"
  db-postgres:
    image: postgres:16
    container_name: ${COMPOSE_PROJECT_NAME}-db
    profiles: ["core", "watchdog", "dogecoin", "api"]
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - 'db_data:/var/lib/postgresql/data'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 20s
      retries: 10

volumes:
  db_data: