/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace IMasterAccountController {
  export type CustomInstructionStruct = {
    targetContract: AddressLike;
    value: BigNumberish;
    data: BytesLike;
  };

  export type CustomInstructionStructOutput = [
    targetContract: string,
    value: bigint,
    data: string
  ] & { targetContract: string; value: bigint; data: string };
}

export declare namespace IPayment {
  export type RequestBodyStruct = {
    transactionId: BytesLike;
    inUtxo: BigNumberish;
    utxo: BigNumberish;
  };

  export type RequestBodyStructOutput = [
    transactionId: string,
    inUtxo: bigint,
    utxo: bigint
  ] & { transactionId: string; inUtxo: bigint; utxo: bigint };

  export type ResponseBodyStruct = {
    blockNumber: BigNumberish;
    blockTimestamp: BigNumberish;
    sourceAddressHash: BytesLike;
    sourceAddressesRoot: BytesLike;
    receivingAddressHash: BytesLike;
    intendedReceivingAddressHash: BytesLike;
    spentAmount: BigNumberish;
    intendedSpentAmount: BigNumberish;
    receivedAmount: BigNumberish;
    intendedReceivedAmount: BigNumberish;
    standardPaymentReference: BytesLike;
    oneToOne: boolean;
    status: BigNumberish;
  };

  export type ResponseBodyStructOutput = [
    blockNumber: bigint,
    blockTimestamp: bigint,
    sourceAddressHash: string,
    sourceAddressesRoot: string,
    receivingAddressHash: string,
    intendedReceivingAddressHash: string,
    spentAmount: bigint,
    intendedSpentAmount: bigint,
    receivedAmount: bigint,
    intendedReceivedAmount: bigint,
    standardPaymentReference: string,
    oneToOne: boolean,
    status: bigint
  ] & {
    blockNumber: bigint;
    blockTimestamp: bigint;
    sourceAddressHash: string;
    sourceAddressesRoot: string;
    receivingAddressHash: string;
    intendedReceivingAddressHash: string;
    spentAmount: bigint;
    intendedSpentAmount: bigint;
    receivedAmount: bigint;
    intendedReceivedAmount: bigint;
    standardPaymentReference: string;
    oneToOne: boolean;
    status: bigint;
  };

  export type ResponseStruct = {
    attestationType: BytesLike;
    sourceId: BytesLike;
    votingRound: BigNumberish;
    lowestUsedTimestamp: BigNumberish;
    requestBody: IPayment.RequestBodyStruct;
    responseBody: IPayment.ResponseBodyStruct;
  };

  export type ResponseStructOutput = [
    attestationType: string,
    sourceId: string,
    votingRound: bigint,
    lowestUsedTimestamp: bigint,
    requestBody: IPayment.RequestBodyStructOutput,
    responseBody: IPayment.ResponseBodyStructOutput
  ] & {
    attestationType: string;
    sourceId: string;
    votingRound: bigint;
    lowestUsedTimestamp: bigint;
    requestBody: IPayment.RequestBodyStructOutput;
    responseBody: IPayment.ResponseBodyStructOutput;
  };

  export type ProofStruct = {
    merkleProof: BytesLike[];
    data: IPayment.ResponseStruct;
  };

  export type ProofStructOutput = [
    merkleProof: string[],
    data: IPayment.ResponseStructOutput
  ] & { merkleProof: string[]; data: IPayment.ResponseStructOutput };
}

export interface IMasterAccountControllerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "encodeCustomInstruction"
      | "executeTransaction"
      | "getPersonalAccount"
      | "registerCustomInstruction"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CustomInstructionRegistered"
      | "ExecutorFeeSet"
      | "InstructionExecuted"
      | "OperatorExecutionWindowSecondsSet"
      | "PersonalAccountCreated"
      | "PersonalAccountImplementationSet"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "encodeCustomInstruction",
    values: [IMasterAccountController.CustomInstructionStruct[]]
  ): string;
  encodeFunctionData(
    functionFragment: "executeTransaction",
    values: [IPayment.ProofStruct, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getPersonalAccount",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "registerCustomInstruction",
    values: [IMasterAccountController.CustomInstructionStruct[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "encodeCustomInstruction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeTransaction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPersonalAccount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerCustomInstruction",
    data: BytesLike
  ): Result;
}

export namespace CustomInstructionRegisteredEvent {
  export type InputTuple = [callHash: BigNumberish];
  export type OutputTuple = [callHash: bigint];
  export interface OutputObject {
    callHash: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ExecutorFeeSetEvent {
  export type InputTuple = [executorFee: BigNumberish];
  export type OutputTuple = [executorFee: bigint];
  export interface OutputObject {
    executorFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InstructionExecutedEvent {
  export type InputTuple = [
    personalAccount: AddressLike,
    xrplOwner: string,
    instructionId: BigNumberish,
    paymentReference: BigNumberish,
    transactionId: BytesLike
  ];
  export type OutputTuple = [
    personalAccount: string,
    xrplOwner: string,
    instructionId: bigint,
    paymentReference: bigint,
    transactionId: string
  ];
  export interface OutputObject {
    personalAccount: string;
    xrplOwner: string;
    instructionId: bigint;
    paymentReference: bigint;
    transactionId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OperatorExecutionWindowSecondsSetEvent {
  export type InputTuple = [newWindowSeconds: BigNumberish];
  export type OutputTuple = [newWindowSeconds: bigint];
  export interface OutputObject {
    newWindowSeconds: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PersonalAccountCreatedEvent {
  export type InputTuple = [xrplOwner: string, personalAccount: AddressLike];
  export type OutputTuple = [xrplOwner: string, personalAccount: string];
  export interface OutputObject {
    xrplOwner: string;
    personalAccount: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PersonalAccountImplementationSetEvent {
  export type InputTuple = [newImplementation: AddressLike];
  export type OutputTuple = [newImplementation: string];
  export interface OutputObject {
    newImplementation: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IMasterAccountController extends BaseContract {
  connect(runner?: ContractRunner | null): IMasterAccountController;
  waitForDeployment(): Promise<this>;

  interface: IMasterAccountControllerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  encodeCustomInstruction: TypedContractMethod<
    [_customInstruction: IMasterAccountController.CustomInstructionStruct[]],
    [bigint],
    "nonpayable"
  >;

  executeTransaction: TypedContractMethod<
    [_proof: IPayment.ProofStruct, _xrplAddress: string],
    [void],
    "payable"
  >;

  getPersonalAccount: TypedContractMethod<
    [_xrplOwner: string],
    [string],
    "nonpayable"
  >;

  registerCustomInstruction: TypedContractMethod<
    [_customInstruction: IMasterAccountController.CustomInstructionStruct[]],
    [bigint],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "encodeCustomInstruction"
  ): TypedContractMethod<
    [_customInstruction: IMasterAccountController.CustomInstructionStruct[]],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "executeTransaction"
  ): TypedContractMethod<
    [_proof: IPayment.ProofStruct, _xrplAddress: string],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "getPersonalAccount"
  ): TypedContractMethod<[_xrplOwner: string], [string], "nonpayable">;
  getFunction(
    nameOrSignature: "registerCustomInstruction"
  ): TypedContractMethod<
    [_customInstruction: IMasterAccountController.CustomInstructionStruct[]],
    [bigint],
    "nonpayable"
  >;

  getEvent(
    key: "CustomInstructionRegistered"
  ): TypedContractEvent<
    CustomInstructionRegisteredEvent.InputTuple,
    CustomInstructionRegisteredEvent.OutputTuple,
    CustomInstructionRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "ExecutorFeeSet"
  ): TypedContractEvent<
    ExecutorFeeSetEvent.InputTuple,
    ExecutorFeeSetEvent.OutputTuple,
    ExecutorFeeSetEvent.OutputObject
  >;
  getEvent(
    key: "InstructionExecuted"
  ): TypedContractEvent<
    InstructionExecutedEvent.InputTuple,
    InstructionExecutedEvent.OutputTuple,
    InstructionExecutedEvent.OutputObject
  >;
  getEvent(
    key: "OperatorExecutionWindowSecondsSet"
  ): TypedContractEvent<
    OperatorExecutionWindowSecondsSetEvent.InputTuple,
    OperatorExecutionWindowSecondsSetEvent.OutputTuple,
    OperatorExecutionWindowSecondsSetEvent.OutputObject
  >;
  getEvent(
    key: "PersonalAccountCreated"
  ): TypedContractEvent<
    PersonalAccountCreatedEvent.InputTuple,
    PersonalAccountCreatedEvent.OutputTuple,
    PersonalAccountCreatedEvent.OutputObject
  >;
  getEvent(
    key: "PersonalAccountImplementationSet"
  ): TypedContractEvent<
    PersonalAccountImplementationSetEvent.InputTuple,
    PersonalAccountImplementationSetEvent.OutputTuple,
    PersonalAccountImplementationSetEvent.OutputObject
  >;

  filters: {
    "CustomInstructionRegistered(uint256)": TypedContractEvent<
      CustomInstructionRegisteredEvent.InputTuple,
      CustomInstructionRegisteredEvent.OutputTuple,
      CustomInstructionRegisteredEvent.OutputObject
    >;
    CustomInstructionRegistered: TypedContractEvent<
      CustomInstructionRegisteredEvent.InputTuple,
      CustomInstructionRegisteredEvent.OutputTuple,
      CustomInstructionRegisteredEvent.OutputObject
    >;

    "ExecutorFeeSet(uint256)": TypedContractEvent<
      ExecutorFeeSetEvent.InputTuple,
      ExecutorFeeSetEvent.OutputTuple,
      ExecutorFeeSetEvent.OutputObject
    >;
    ExecutorFeeSet: TypedContractEvent<
      ExecutorFeeSetEvent.InputTuple,
      ExecutorFeeSetEvent.OutputTuple,
      ExecutorFeeSetEvent.OutputObject
    >;

    "InstructionExecuted(address,string,uint256,uint256,bytes32)": TypedContractEvent<
      InstructionExecutedEvent.InputTuple,
      InstructionExecutedEvent.OutputTuple,
      InstructionExecutedEvent.OutputObject
    >;
    InstructionExecuted: TypedContractEvent<
      InstructionExecutedEvent.InputTuple,
      InstructionExecutedEvent.OutputTuple,
      InstructionExecutedEvent.OutputObject
    >;

    "OperatorExecutionWindowSecondsSet(uint256)": TypedContractEvent<
      OperatorExecutionWindowSecondsSetEvent.InputTuple,
      OperatorExecutionWindowSecondsSetEvent.OutputTuple,
      OperatorExecutionWindowSecondsSetEvent.OutputObject
    >;
    OperatorExecutionWindowSecondsSet: TypedContractEvent<
      OperatorExecutionWindowSecondsSetEvent.InputTuple,
      OperatorExecutionWindowSecondsSetEvent.OutputTuple,
      OperatorExecutionWindowSecondsSetEvent.OutputObject
    >;

    "PersonalAccountCreated(string,address)": TypedContractEvent<
      PersonalAccountCreatedEvent.InputTuple,
      PersonalAccountCreatedEvent.OutputTuple,
      PersonalAccountCreatedEvent.OutputObject
    >;
    PersonalAccountCreated: TypedContractEvent<
      PersonalAccountCreatedEvent.InputTuple,
      PersonalAccountCreatedEvent.OutputTuple,
      PersonalAccountCreatedEvent.OutputObject
    >;

    "PersonalAccountImplementationSet(address)": TypedContractEvent<
      PersonalAccountImplementationSetEvent.InputTuple,
      PersonalAccountImplementationSetEvent.OutputTuple,
      PersonalAccountImplementationSetEvent.OutputObject
    >;
    PersonalAccountImplementationSet: TypedContractEvent<
      PersonalAccountImplementationSetEvent.InputTuple,
      PersonalAccountImplementationSetEvent.OutputTuple,
      PersonalAccountImplementationSetEvent.OutputObject
    >;
  };
}
