/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IMasterAccountController } from "./IMasterAccountController";
export type { IPersonalAccount } from "./IPersonalAccount";
