/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  FunctionFragment,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
} from "../common";

export interface IPersonalAccountInterface extends Interface {
  getEvent(
    nameOrSignatureOrTopic:
      | "Approved"
      | "CollateralReserved"
      | "Deposited"
      | "Redeemed"
      | "WithdrawalClaimed"
      | "Withdrawn"
  ): EventFragment;
}

export namespace ApprovedEvent {
  export type InputTuple = [
    fxrp: AddressLike,
    vault: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [fxrp: string, vault: string, amount: bigint];
  export interface OutputObject {
    fxrp: string;
    vault: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CollateralReservedEvent {
  export type InputTuple = [
    lots: BigNumberish,
    agentVault: AddressLike,
    executor: AddressLike,
    executorFee: BigNumberish,
    reservationId: BigNumberish
  ];
  export type OutputTuple = [
    lots: bigint,
    agentVault: string,
    executor: string,
    executorFee: bigint,
    reservationId: bigint
  ];
  export interface OutputObject {
    lots: bigint;
    agentVault: string;
    executor: string;
    executorFee: bigint;
    reservationId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositedEvent {
  export type InputTuple = [
    vault: AddressLike,
    amount: BigNumberish,
    actualAmount: BigNumberish
  ];
  export type OutputTuple = [
    vault: string,
    amount: bigint,
    actualAmount: bigint
  ];
  export interface OutputObject {
    vault: string;
    amount: bigint;
    actualAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RedeemedEvent {
  export type InputTuple = [
    lots: BigNumberish,
    executor: AddressLike,
    executorFee: BigNumberish
  ];
  export type OutputTuple = [
    lots: bigint,
    executor: string,
    executorFee: bigint
  ];
  export interface OutputObject {
    lots: bigint;
    executor: string;
    executorFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawalClaimedEvent {
  export type InputTuple = [
    vault: AddressLike,
    rewardEpochId: BigNumberish,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    vault: string,
    rewardEpochId: bigint,
    amount: bigint
  ];
  export interface OutputObject {
    vault: string;
    rewardEpochId: bigint;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawnEvent {
  export type InputTuple = [
    vault: AddressLike,
    amount: BigNumberish,
    actualAmount: BigNumberish
  ];
  export type OutputTuple = [
    vault: string,
    amount: bigint,
    actualAmount: bigint
  ];
  export interface OutputObject {
    vault: string;
    amount: bigint;
    actualAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IPersonalAccount extends BaseContract {
  connect(runner?: ContractRunner | null): IPersonalAccount;
  waitForDeployment(): Promise<this>;

  interface: IPersonalAccountInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getEvent(
    key: "Approved"
  ): TypedContractEvent<
    ApprovedEvent.InputTuple,
    ApprovedEvent.OutputTuple,
    ApprovedEvent.OutputObject
  >;
  getEvent(
    key: "CollateralReserved"
  ): TypedContractEvent<
    CollateralReservedEvent.InputTuple,
    CollateralReservedEvent.OutputTuple,
    CollateralReservedEvent.OutputObject
  >;
  getEvent(
    key: "Deposited"
  ): TypedContractEvent<
    DepositedEvent.InputTuple,
    DepositedEvent.OutputTuple,
    DepositedEvent.OutputObject
  >;
  getEvent(
    key: "Redeemed"
  ): TypedContractEvent<
    RedeemedEvent.InputTuple,
    RedeemedEvent.OutputTuple,
    RedeemedEvent.OutputObject
  >;
  getEvent(
    key: "WithdrawalClaimed"
  ): TypedContractEvent<
    WithdrawalClaimedEvent.InputTuple,
    WithdrawalClaimedEvent.OutputTuple,
    WithdrawalClaimedEvent.OutputObject
  >;
  getEvent(
    key: "Withdrawn"
  ): TypedContractEvent<
    WithdrawnEvent.InputTuple,
    WithdrawnEvent.OutputTuple,
    WithdrawnEvent.OutputObject
  >;

  filters: {
    "Approved(address,address,uint256)": TypedContractEvent<
      ApprovedEvent.InputTuple,
      ApprovedEvent.OutputTuple,
      ApprovedEvent.OutputObject
    >;
    Approved: TypedContractEvent<
      ApprovedEvent.InputTuple,
      ApprovedEvent.OutputTuple,
      ApprovedEvent.OutputObject
    >;

    "CollateralReserved(uint256,address,address,uint256,uint256)": TypedContractEvent<
      CollateralReservedEvent.InputTuple,
      CollateralReservedEvent.OutputTuple,
      CollateralReservedEvent.OutputObject
    >;
    CollateralReserved: TypedContractEvent<
      CollateralReservedEvent.InputTuple,
      CollateralReservedEvent.OutputTuple,
      CollateralReservedEvent.OutputObject
    >;

    "Deposited(address,uint256,uint256)": TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;
    Deposited: TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;

    "Redeemed(uint256,address,uint256)": TypedContractEvent<
      RedeemedEvent.InputTuple,
      RedeemedEvent.OutputTuple,
      RedeemedEvent.OutputObject
    >;
    Redeemed: TypedContractEvent<
      RedeemedEvent.InputTuple,
      RedeemedEvent.OutputTuple,
      RedeemedEvent.OutputObject
    >;

    "WithdrawalClaimed(address,uint256,uint256)": TypedContractEvent<
      WithdrawalClaimedEvent.InputTuple,
      WithdrawalClaimedEvent.OutputTuple,
      WithdrawalClaimedEvent.OutputObject
    >;
    WithdrawalClaimed: TypedContractEvent<
      WithdrawalClaimedEvent.InputTuple,
      WithdrawalClaimedEvent.OutputTuple,
      WithdrawalClaimedEvent.OutputObject
    >;

    "Withdrawn(address,uint256,uint256)": TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
    Withdrawn: TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
  };
}
