/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IMasterAccountController__factory } from "./IMasterAccountController__factory";
export { IPersonalAccount__factory } from "./IPersonalAccount__factory";
