/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IPersonalAccount,
  IPersonalAccountInterface,
} from "../../smartAccount/IPersonalAccount";

const _abi = [
  {
    type: "event",
    name: "Approved",
    inputs: [
      {
        name: "fxrp",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "vault",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "CollateralReserved",
    inputs: [
      {
        name: "lots",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "agentVault",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "executor",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "executorFee",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "reservationId",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Deposited",
    inputs: [
      {
        name: "vault",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "actualAmount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Redeemed",
    inputs: [
      {
        name: "lots",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "executor",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "executorFee",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "WithdrawalClaimed",
    inputs: [
      {
        name: "vault",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "rewardEpochId",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Withdrawn",
    inputs: [
      {
        name: "vault",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "actualAmount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "error",
    name: "AgentNotAvailable",
    inputs: [],
  },
  {
    type: "error",
    name: "AlreadyInitialized",
    inputs: [],
  },
  {
    type: "error",
    name: "ApprovalFailed",
    inputs: [],
  },
  {
    type: "error",
    name: "CustomInstructionCallFailed",
    inputs: [],
  },
  {
    type: "error",
    name: "FxrpAssetManagerNotSet",
    inputs: [],
  },
  {
    type: "error",
    name: "InsufficientFundsForCollateralReservation",
    inputs: [
      {
        name: "collateralReservationFee",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "InsufficientFundsForRedeemExecutor",
    inputs: [],
  },
  {
    type: "error",
    name: "InvalidControllerAddress",
    inputs: [],
  },
  {
    type: "error",
    name: "InvalidXrplOwner",
    inputs: [],
  },
  {
    type: "error",
    name: "OnlyController",
    inputs: [],
  },
] as const;

export class IPersonalAccount__factory {
  static readonly abi = _abi;
  static createInterface(): IPersonalAccountInterface {
    return new Interface(_abi) as IPersonalAccountInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IPersonalAccount {
    return new Contract(address, _abi, runner) as unknown as IPersonalAccount;
  }
}
